controller_list:
#  - name: ""
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    joints:
#      - shoulder_pan_joint
#      - shoulder_lift_joint
#      - elbow_joint
#      - wrist_1_joint
#      - wrist_2_joint
#      - wrist_3_joint
  - name: "traj_or_jog_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: "compliance_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    compliance_command_timeout: test
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint